# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enterprise_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('datatype', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('units', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeToVisualization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_enterprise_id', models.IntegerField()),
                ('visual_enterprise_id', models.IntegerField()),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IPFIX_visualization.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enterprise_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('function', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='visualization',
            unique_together=set([('id', 'enterprise_id')]),
        ),
        migrations.AddField(
            model_name='typetovisualization',
            name='visual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IPFIX_visualization.Visualization'),
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together=set([('id', 'enterprise_id')]),
        ),
    ]
